USE Productions_MSCRM;

UPDATE new_projectExtensionBase
SET 
	cust_estverintchannelverint_oqm_pm = 4,
	cust_estverintchannelverint_oqm_se = 8,
	cust_estverintchannelverint_oqm_wfmse = 1,
	cust_estverintchannelverint_oqm_solndesign = 0.5,
	cust_estverintchannelverint_oqm_psesi = 3, 
	cust_estverintchannelverint_oqm_trainvln = 5,
	cust_estverintchannelverint_oqm_trainadtech = 1,
	cust_estverintchannelverint_oqm_appconsulting = 1,
	
	cust_estverintchannelverint_orec_pm = 3,
	cust_estverintchannelverint_orec_se =4,
	cust_estverintchannelverint_orec_wfmse = 0,
	cust_estverintchannelverint_orec_solndesign = 0.5,
	cust_estverintchannelverint_orec_psesi = 2,
	cust_estverintchannelverint_orec_trainvln = 2,
	cust_estverintchannelverint_orec_trainadtech = 0,
	cust_estverintchannelverint_orec_appconsulting = 1, 
	
	cust_estverintchannelverint_owfm_pm = 3,
	cust_estverintchannelverint_owfm_se = 0,
	cust_estverintchannelverint_owfm_wfmse = 4,
	cust_estverintchannelverint_owfm_solndesign = 2,
	cust_estverintchannelverint_owfm_psesi = 2,
	cust_estverintchannelverint_owfm_trainvln = 0,
	cust_estverintchannelverint_owfm_trainadtech = 9,
	cust_estverintchannelverint_owfm_appconsulting = 0,
	
	cust_estverintchannelverint_owfo_pm = 5,
	cust_estverintchannelverint_owfo_se = 8,
	cust_estverintchannelverint_owfo_wfmse = 5,
	cust_estverintchannelverint_owfo_solndesign = 2.5,
	cust_estverintchannelverint_owfo_psesi = 3.5,
	cust_estverintchannelverint_owfo_trainvln = 5,  
	cust_estverintchannelverint_owfo_trainadtech = 9,
	cust_estverintchannelverint_owfo_appconsulting = 0,
	
	cust_estverintdirectverint_oqm_pm = 6,
	cust_estverintdirectverint_oqm_se = 8,
	cust_estverintdirectverint_oqm_wfmse = 1,
	cust_estverintdirectverint_oqm_solndesign = 0.5,
	cust_estverintdirectverint_oqm_psesi = 3,
	cust_estverintdirectverint_oqm_trainvln = 5,
	cust_estverintdirectverint_oqm_trainadtech = 1,
	cust_estverintdirectverint_oqm_appconsulting = 2,
	
	cust_estverintdirectverint_orec_pm = 5,
	cust_estverintdirectverint_orec_se = 4,
	cust_estverintdirectverint_orec_wfmse = 0, 
	cust_estverintdirectverint_orec_solndesign = 0.5, 
	cust_estverintdirectverint_orec_psesi = 2,
	cust_estverintdirectverint_orec_trainvln = 2, 
	cust_estverintdirectverint_orec_trainadtech = 0, 
	cust_estverintdirectverint_orec_appconsulting = 2,
	
	cust_estverintdirectverint_owfm_pm = 5,
	cust_estverintdirectverint_owfm_se = 0,
	cust_estverintdirectverint_owfm_wfmse = 4,
	cust_estverintdirectverint_owfm_solndesign = 2, 
	cust_estverintdirectverint_owfm_psesi = 2,
	cust_estverintdirectverint_owfm_trainvln = 0, 
	cust_estverintdirectverint_owfm_trainadtech = 9,
	cust_estverintdirectverint_owfm_appconsulting = 0,
	
	cust_estverintdirectverint_owfo_pm = 7,
	cust_estverintdirectverint_owfo_se = 8,
	cust_estverintdirectverint_owfo_wfmse = 5, 
	cust_estverintdirectverint_owfo_solndesign = 2.5, 
	cust_estverintdirectverint_owfo_psesi = 3.5,
	cust_estverintdirectverint_owfo_trainvln = 5,
	cust_estverintdirectverint_owfo_trainadtech = 9, 
	cust_estverintdirectverint_owfo_appconsulting = 6,
	
	cust_estverintchannelsky_oqm_pm = 3,
	cust_estverintchannelsky_oqm_se = 4,
	cust_estverintchannelsky_oqm_wfmse = 1, 
	cust_estverintchannelsky_oqm_solndesign = 0.5, 
	cust_estverintchannelsky_oqm_psesi = 1.5,
	cust_estverintchannelsky_oqm_trainvln = 5,
	cust_estverintchannelsky_oqm_trainadtech = 1, 
	cust_estverintchannelsky_oqm_appconsulting = 0,
	
	cust_estverintchannelsky_orec_pm = 2,
	cust_estverintchannelsky_orec_se = 3,
	cust_estverintchannelsky_orec_wfmse = 0, 
	cust_estverintchannelsky_orec_solndesign = 0.5, 
	cust_estverintchannelsky_orec_psesi = 1.5,
	cust_estverintchannelsky_orec_trainvln = 2,
	cust_estverintchannelsky_orec_trainadtech = 0,
	cust_estverintchannelsky_orec_appconsulting = 0,
	
	cust_estverintchannelsky_owfm_pm = 1,
	cust_estverintchannelsky_owfm_se = 0,
	cust_estverintchannelsky_owfm_wfmse = 4,
	cust_estverintchannelsky_owfm_solndesign = 1,
	cust_estverintchannelsky_owfm_psesi = 1.5,
	cust_estverintchannelsky_owfm_trainvln = 0,
	cust_estverintchannelsky_owfm_trainadtech = 9,
	cust_estverintchannelsky_owfm_appconsulting = 0,
	
	cust_estverintchannelsky_owfo_pm = 2,
	cust_estverintchannelsky_owfo_se = 2,
	cust_estverintchannelsky_owfo_wfmse = 5,
	cust_estverintchannelsky_owfo_solndesign = 2,
	cust_estverintchannelsky_owfo_psesi = 3,
	cust_estverintchannelsky_owfo_trainvln = 5,
	cust_estverintchannelsky_owfo_trainadtech = 9,
	cust_estverintchannelsky_owfo_appconsulting = 0,

	cust_estverintdirectsky_oqm_pm = 4,
	cust_estverintdirectsky_oqm_se = 4,
	cust_estverintdirectsky_oqm_wfmse = 1,
	cust_estverintdirectsky_oqm_solndesign = 0.5,
	cust_estverintdirectsky_oqm_psesi = 1.5,
	cust_estverintdirectsky_oqm_trainvln = 5,
	cust_estverintdirectsky_oqm_trainadtech = 1,
	cust_estverintdirectsky_oqm_appconsulting = 0,
	
	cust_estverintdirectsky_orec_pm = 3,
	cust_estverintdirectsky_orec_se = 3,
	cust_estverintdirectsky_orec_wfmse = 0,
	cust_estverintdirectsky_orec_solndesign = 0.5,
	cust_estverintdirectsky_orec_psesi = 1.5,
	cust_estverintdirectsky_orec_trainvln = 2,
	cust_estverintdirectsky_orec_trainadtech = 0,
	cust_estverintdirectsky_orec_appconsulting = 0,
	
	cust_estverintdirectsky_owfm_pm = 2,
	cust_estverintdirectsky_owfm_se = 0,
	cust_estverintdirectsky_owfm_wfmse = 4,
	cust_estverintdirectsky_owfm_solndesign = 1,
	cust_estverintdirectsky_owfm_psesi = 1.5,
	cust_estverintdirectsky_owfm_trainvln = 0,
	cust_estverintdirectsky_owfm_trainadtech = 9,
	cust_estverintdirectsky_owfm_appconsulting = 0,
	
	cust_estverintdirectsky_owfo_pm = 3,
	cust_estverintdirectsky_owfo_se = 2,
	cust_estverintdirectsky_owfo_wfmse = 5,
	cust_estverintdirectsky_owfo_solndesign = 2,
	cust_estverintdirectsky_owfo_psesi = 2,
	cust_estverintdirectsky_owfo_trainvln = 5,
	cust_estverintdirectsky_owfo_trainadtech = 9,
	cust_estverintdirectsky_owfo_appconsulting = 0
	
FROM new_projectExtensionBase
WHERE cust_estverintchannelverint_oqm_pm IS NULL;